# Generated by Django 4.1 on 2022-08-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/', verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='file_upload',
            field=models.BooleanField(default=False, verbose_name='امکان بارگذاری فایل'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='microphone',
            field=models.BooleanField(default=False, verbose_name='امکان اتصال میکروفون'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='screen',
            field=models.BooleanField(default=False, verbose_name='امکان اشتراک صفحه'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='webcam',
            field=models.BooleanField(default=False, verbose_name='امکان اتصال دوربین'),
        ),
    ]
