# Generated by Django 4.1 on 2022-08-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customusers_avatar_customusers_file_upload_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='file_upload',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='microphone',
            field=models.BooleanField(default=False, verbose_name='اتصال میکروفون'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='screen',
            field=models.BooleanField(default=False, verbose_name='اشتراک صفحه'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='webcam',
            field=models.BooleanField(default=False, verbose_name='اتصال دوربین'),
        ),
    ]
