# Generated by Django 4.0.3 on 2022-04-21 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('OMO', 'یک ماهه'), ('TMO', 'سه ماهه'), ('SMO', 'شش ماهه'), ('OYR', 'یک ساله')], default='OMO', max_length=3),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
