# Generated by Django 4.0.3 on 2022-04-21 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_service_start_date_service_status_alter_plan_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='period',
            field=models.CharField(choices=[('OMO', 1), ('TMO', 3), ('SMO', 6), ('OYR', 12)], default='OMO', max_length=3),
        ),
    ]
