# Generated by Django 4.0.3 on 2022-04-22 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_alter_room_service'),
        ('user', '0002_remove_customuser_role_customuser_membership_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser_Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OPT', 'اپراتور'), ('PRS', 'ارائه دهنده'), ('GUT', 'مهمان')], default='GUT', max_length=3)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRoom', to='room.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
