# Generated by Django 4.1 on 2022-08-04 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان کلاس')),
                ('status', models.CharField(choices=[('HLD', 'در حال برگزاری'), ('CLS', 'بسته'), ('RMV', 'حذف شده')], default='CLS', max_length=3, verbose_name='وضعیت')),
                ('allow_guests', models.BooleanField(default=True, verbose_name='امکان ورود مهمان')),
                ('operator_first', models.BooleanField(default=True, verbose_name='بازگشایی با ورود اپراتور')),
                ('automatic_ending', models.BooleanField(default=False, verbose_name='پایان خودکار')),
                ('duration', models.IntegerField(default=0, verbose_name='مدت زمان')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_organizer', to='accounts.organizerusers', verbose_name='برگزار کننده')),
            ],
            options={
                'verbose_name': 'اتاق',
                'verbose_name_plural': 'اتاق\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000, verbose_name='محتوا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_room', to='panel.rooms', verbose_name='اتاق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_user', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان فایل')),
                ('file_content', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='فایل')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_room', to='panel.rooms', verbose_name='اتاق')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_user', to=settings.AUTH_USER_MODEL, verbose_name='بارگذاری کننده')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ContributorRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_type', models.CharField(choices=[('OPT', 'اپراتور'), ('NRM', 'عادی'), ('GST', 'مهمان')], default='NRM', max_length=3, verbose_name='نوع شرکت کننده')),
                ('contribution_start_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_contributor_room', to='panel.rooms', verbose_name='اتاق')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_contributor_user', to='accounts.contributorusers', verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'شرکت کننده اتاق',
                'verbose_name_plural': 'شرکت کنندگان اتاق\u200cها',
            },
        ),
    ]
