# Generated by Django 4.1 on 2022-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='microphone',
            field=models.BooleanField(default=False, verbose_name='میکروفون'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='screen',
            field=models.BooleanField(default=False, verbose_name='اشتراک گذاری صفحه'),
        ),
        migrations.AddField(
            model_name='rooms',
            name='webcam',
            field=models.BooleanField(default=False, verbose_name='دوربین'),
        ),
    ]
