# Generated by Django 4.1 on 2022-08-17 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_messages_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NRM', 'عادی'), ('RMV', 'حذف شده')], default='NRM', max_length=3, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
        ),
        migrations.AddField(
            model_name='messages',
            name='status',
            field=models.CharField(choices=[('NRM', 'عادی'), ('RMV', 'حذف شده')], default='NRM', max_length=3, verbose_name='وضعیت'),
        ),
        migrations.AddField(
            model_name='messages',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_chat', to='panel.chats', verbose_name='چت'),
        ),
    ]
