# Generated by Django 4.1 on 2022-08-17 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_chats_messages_status_messages_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
