# Generated by Django 4.0.3 on 2022-04-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0003_alter_plan_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('status', models.BooleanField(default=False)),
                ('users_number_limitation', models.BigIntegerField()),
                ('session_duration', models.BigIntegerField()),
                ('accept_guest', models.BooleanField()),
                ('operator_enter', models.BooleanField()),
                ('used_time', models.TimeField(blank=True, null=True)),
                ('total_used_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
    ]
